name: Rust Setup
description: Configure Rust environment with zigbuild
inputs:
  target:
    description: Cross-compilation target
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Zig toolchain
      uses: korandoru/setup-zig@v1
      with:
        zig-version: 0.11.0

    - name: Install cargo-zigbuild
      shell: bash
      run: cargo install cargo-zigbuild

    - name: Set Rust target
      if: inputs.target != ''
      shell: bash
      run: |
        echo "CARGO_BUILD_TARGET=${{ inputs.target }}" >> $GITHUB_ENV
        echo "CARGO_TARGET_DIR=./target/zig" >> $GITHUB_ENV
